### PR TITLE
Update Cocoapods spec

### PR DESCRIPTION
**Pull request by rizwankce**
Lots of things changed after opening #16 
New React Native version defaults to cocoa pods now. So making some changes on podspec. All of the changes are inspired from react native community projects. 

- Moves the pod spec file to the root directory (Pods standard way)
- Updates the pod spec to get the details from `package.json`

### CODE REVIEW

**Comment by pushy-me** [comment]
Hi @rizwankce,
Thanks for your contribution!

Does the project still support `react-native link` when you move the `Podspec` to the root directory, and does it support the dynamic `Podspec` format you introduced?

**Comment by rizwankce** [comment]
@pushy-me `react-native link` directly integrate the project itself. So it will not affect anything. Let me verify that with a sample project and let you know

**Comment by odellamaggiore** [comment]
Hi @rizwankce,

We also need to install pushy-react-native as a Cocoa Pod in our project (RN 0.61.2). How to install it  if we use your updated podspec file ? Do we still have to link the lib with` react-native link` ?
Thanks !

**Comment by rizwankce** [comment]
@odellamaggiore 

Starting from RN v0.59 `react-native link` will automatically use cocoapods if it detects `podfile` in the root directory of dependencies. 

Check React Native [Linking Libraries](https://facebook.github.io/react-native/docs/0.60/linking-libraries-ios) doc for more info.

**Comment by pushy-me** [comment]
Hi @rizwankce,
Thanks for your work on this! 

PR merged and published in `1.0.9` 🎉

**Comment by rizwankce** [comment]
@pushy-me Happy to help. 😄  I didn't have time to test this with a sample project. However we are going to integrate the new v1.0.9 to our main app and let you know if we face any issues or everything goes fine.

I will also watch this repo for new issues - just in case if my change break some basic functionalities.

**Comment by bitsydarel** [comment]
It's seems this has some breaking changes

**Comment by rizwankce** [comment]
@bitsydarel May I know what kind of issues you are facing? is it linking error?

**Comment by pushy-me** [comment]
@bitsydarel You may also reach out to us at support@pushy.me and we will be glad to help.

**Pull request merged**
